image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 12 x64
  - npm install

build_script:
  - npm run dist
  - name: Publish
    run: |
      npm run dist
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

